# Generated by Django 3.0.2 on 2020-01-30 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyclubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=1000)),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip Code')),
                ('phone', models.CharField(max_length=20, verbose_name='Cell Phone')),
                ('web', models.URLField(verbose_name='Web address')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(to='events.MyclubUser')),
                ('venue', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue')),
            ],
        ),
    ]
